M48
; DRILL file {KiCad (6.0.0)} date Sat Oct 15 12:08:09 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-15T12:08:09+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X1.4803Y-3.4941
X1.4803Y-3.7618
T2
X5.1575Y-3.5866
X5.1575Y-3.9008
T0
M30
