M48
; DRILL file {KiCad (6.0.0)} date Sun May  8 19:44:57 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-08T19:44:57+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.748Y-2.4291
X5.0157Y-2.4291
T2
X5.1575Y-3.5866
X5.1575Y-3.9008
T0
M30
